// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function appendSchema(url: string | undefined): string | undefined {
  if (!url) return url
  const sep = url.includes('?') ? '&' : '?'
  // portfolio schema + no TLS (Railway internal network)
  return `${url}${sep}schema=portfolio&sslmode=disable`
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: appendSchema(process.env["DATABASE_URL"]),
  },
});
